name: ioe_mobile_app
description: "A comprehensive attendance portal for IOE."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  http: ^1.4.0
  camera: ^0.11.2  # For camera access
  google_mlkit_face_detection: ^0.13.1 # To find faces in the image
  tflite_flutter: ^0.11.0             # To run the face recognition model
  image: ^4.1.0 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    # - assets/models/mobile_facenet.tflite